version: '2'
services:
  web:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - redis
  db:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
  redis:
    image: redis:2.8
    restart: always
    ports:
      - "6379:6379"