version: '2'
services:
  web:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8080:8080"
    links:
      - redis
  redis:
    image: redis:2.8
    restart: always
    ports:
      - "6379:6379"